import json
import re
import time

import boto3

from app.core.config import settings


def _bedrock_boto3_kwargs() -> dict:
    """Return boto3 keyword args for Bedrock clients.

    If BEDROCK_CROSS_ACCOUNT_ROLE_ARN is configured, assumes that role first
    (cross-account access to company Bedrock) and returns short-lived credentials.
    Otherwise returns an empty dict so boto3 uses the pod's IRSA role directly.
    """
    if not settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN:
        return {}
    sts = boto3.client("sts", region_name=settings.AWS_REGION)
    assumed = sts.assume_role(
        RoleArn=settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN,
        RoleSessionName="agora-worker-bedrock",
        DurationSeconds=3600,
    )
    creds = assumed["Credentials"]
    return {
        "aws_access_key_id": creds["AccessKeyId"],
        "aws_secret_access_key": creds["SecretAccessKey"],
        "aws_session_token": creds["SessionToken"],
    }


class BedrockRemediationClient:
    """Calls AWS Bedrock (Amazon Nova) to analyze CI failures and produce fixes.

    Uses the model-agnostic Converse API rather than ``invoke_model`` so swapping
    ``BEDROCK_MODEL_ID`` to a different model family doesn't require touching the
    request/response shape here.
    """

    def __init__(self) -> None:
        self._client = boto3.client(
            "bedrock-runtime",
            region_name=settings.AWS_REGION,
            **_bedrock_boto3_kwargs(),
        )
        self._model_id = settings.BEDROCK_MODEL_ID

    def _build_prompt(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> str:
        return f"""You are an expert DevOps engineer specializing in GitHub Actions CI/CD pipelines.

A workflow named "{workflow_name}" in repository "{repo}" has failed.

## Failed Workflow YAML
```yaml
{workflow_yaml}
```

## Failure Logs (last 300 lines)
```
{logs}
```

Analyze the failure and provide a fix. Respond with ONLY valid JSON in this exact format:
{{
  "root_cause": "One clear sentence describing why the workflow failed",
  "fixed_yaml": "The complete corrected workflow YAML as a string",
  "pr_title": "fix: <short description of the fix>",
  "pr_description": "## Root Cause\\n<root_cause>\\n\\n## Changes Made\\n- bullet point changes\\n\\n## Testing\\nThis fix was generated by PipelineIQ AI using AWS Bedrock (Amazon Nova). Please review the changes before merging.\\n\\n> 🤖 Auto-generated by [PipelineIQ](https://github.com/pipelineiq)"
}}"""

    def analyze_failure(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> dict:
        """
        Call Bedrock to analyze the workflow failure.

        Returns:
            A dict with keys: root_cause, fixed_yaml, pr_title, pr_description.

        Raises:
            Exception: If the model cannot be invoked after retries or the response
                       cannot be parsed as valid JSON.
        """
        prompt = self._build_prompt(workflow_yaml, logs, workflow_name, repo)

        max_retries = 2
        last_exception: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[
                        {
                            "role": "user",
                            "content": [{"text": prompt}],
                        }
                    ],
                    inferenceConfig={"maxTokens": 8192},
                )
                raw_text: str = response["output"]["message"]["content"][0]["text"].strip()

                raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
                raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
                raw_text = raw_text.strip()

                parsed: dict = json.loads(raw_text)

                required_keys = {"root_cause", "fixed_yaml", "pr_title", "pr_description"}
                missing = required_keys - set(parsed.keys())
                if missing:
                    raise ValueError(f"Bedrock response missing keys: {missing}")

                return parsed

            except self._client.exceptions.ThrottlingException as exc:
                last_exception = exc
                if attempt < max_retries:
                    wait = 2 ** (attempt + 1)
                    time.sleep(wait)
                    continue
                raise

            except (json.JSONDecodeError, ValueError, KeyError) as exc:
                _raw = locals().get("raw_text", "<unavailable>")
                raise RuntimeError(
                    f"Failed to parse Bedrock response as valid JSON: {exc}\n"
                    f"Raw response: {_raw}"
                ) from exc

        raise RuntimeError("Bedrock invocation failed after retries") from last_exception

    def generate_yaml_fix(self, workflow_yaml: str, root_cause: str) -> str:
        """Directly generate a corrected workflow YAML via the Converse API.

        Used as a fallback when the yaml_fixer Bedrock Agent returns a capability
        refusal instead of actual YAML (e.g. its system prompt restricts it from
        writing files). This path calls the model directly — no agent, no tool use.

        Returns:
            The corrected YAML as a string.
        Raises:
            RuntimeError: If the model refuses or returns unusable output.
        """
        prompt = (
            "You are an expert GitHub Actions DevOps engineer fixing a broken CI workflow.\n\n"
            f"ROOT CAUSE: {root_cause}\n\n"
            "ORIGINAL FAILING YAML:\n"
            "```yaml\n"
            f"{workflow_yaml}\n"
            "```\n\n"
            "CANONICAL STABLE VERSIONS (use these when a version is invalid or missing):\n"
            "  Python  → 3.12\n"
            "  Node.js → 20\n"
            "  Java    → 21\n"
            "  Ruby    → 3.3\n"
            "  Go      → 1.22\n"
            "  Rust    → stable\n"
            "  Ubuntu  → ubuntu-22.04\n"
            "  actions/checkout        → v4\n"
            "  actions/setup-python    → v5\n"
            "  actions/setup-node      → v4\n"
            "  actions/setup-java      → v4\n"
            "  actions/upload-artifact → v4\n\n"
            "STRICT RULES — violating any rule makes your response invalid:\n"
            "1. Output ONLY the corrected YAML. Zero prose. Zero explanation.\n"
            "2. Do NOT use markdown fences (no ```).\n"
            "3. Do NOT ask questions or say you need more information.\n"
            "4. Do NOT say 'I need to ask' or 'please provide' or 'I cannot determine'.\n"
            "5. If a version number is clearly invalid (e.g. '99', '0', 'latest'), "
            "replace it with the canonical stable version from the table above.\n"
            "6. Make the MINIMAL change required — keep every other line identical.\n"
            "7. Your first output character must be 'n' (start of 'name:') or '-' or 'o' (start of 'on:').\n\n"
            "Output the corrected YAML now:"
        )
        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[{"role": "user", "content": [{"text": prompt}]}],
                    inferenceConfig={"maxTokens": 8192},
                )
                raw: str = response["output"]["message"]["content"][0]["text"].strip()
                # Strip any accidental markdown fences
                if raw.startswith("```"):
                    lines = raw.splitlines()
                    raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
                if not raw:
                    raise ValueError("Model returned empty YAML fix")
                return raw
            except self._client.exceptions.ThrottlingException:
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
        raise RuntimeError("generate_yaml_fix: Bedrock invocation failed after retries")
